title: "Better than brian is a web consulting service. Let us help you get your web presence dialed in. Don't let Brian near your code."
email: "info@betterthanbrian.com"
description: >- # this means to ignore newlines until "baseurl:"
 Better than brian is a web consulting service. Let us help you get your web presence dialed in. Don't let Brian near your code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://betterthanbrian.com" # the base hostname & protocol for your site, e.g. http://example.com or  https://tradejk.netlify.com
twitter_url: https://twitter.com/better_than_bri
linkedin_url: https://www.linkedin.com/company/28590312/admin/
timezone: America/Denver 

# Google Analytics
google_analytics: G-P39V41QRY7

logo: "/assets/img/logo/logo.png"
logo_2: "/assets/img/logo/logo_2.png"
# mailchimp_list: "https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35"
# mailchimp_input_name: "b_307862c135e4548eecf86f389_342411fb35"
sass:
    sass_dir: _sass
    style: compressed

permalink:  "/pages/blog/:title"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

cover_image: "/assets/img/bg/medium.jpg"


#collections
collections:
  authors:
    output: true
    permalink: author/:title/
  features:
    output: true
  services:
    output: true

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
  -
    scope:
      path: ""
      type: posts
    values:
      author: matt_macchia

paginate: 6  # Number of posts per page
paginate_path: "/pages/blog/page:num/"

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

feed:
  collections:
    posts:
      path: "/index.xml"
